In [ ]:
import requests

headers = {
    'sec-ch-ua-platform': '"Windows"',
    'Referer': 'https://www.fotmob.com/en-GB/players/1037128/dylan-tait',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
    'x-mas': 'eyJib2R5Ijp7InVybCI6Ii9hcGkvZGF0YS9wbGF5ZXJEYXRhP2lkPTEwMzcxMjgiLCJjb2RlIjoxNzg0MzgyNzI2NjU4LCJmb28iOiJwcm9kdWN0aW9uOmE5NjhhMWRhM2UxZGIwZmY2ZjFlZjE4YzNlYjFjZTNkZWE0YWViZTYifSwic2lnbmF0dXJlIjoiNjJCNzQ0REE1NUIzMTVDQjYxQTQ3MDFBRTNGODhEMzcifQ==',
    'sec-ch-ua': '"Not;A=Brand";v="8", "Chromium";v="150", "Google Chrome";v="150"',
    'sec-ch-ua-mobile': '?0',
}

params = {
    'id': '1037128',
}

response = requests.get('https://www.fotmob.com/api/data/playerData', params=params, headers=headers)

In [ ]:
import os

os.chdir('/content/drive/MyDrive/Football Data Analysis/Dylan Tait')

In [ ]:
import pandas as pd

data = response.json()

data.keys()

dict_keys(['id', 'name', 'birthDate', 'isCoach', 'isCaptain', 'gender', 'primaryTeam', 'positionDescription', 'injuryInformation', 'internationalDuty', 'playerInformation', 'mainLeague', 'trophies', 'recentMatches', 'careerHistory', 'traits', 'meta', 'coachStats', 'statSeasons', 'firstSeasonStats', 'status', 'marketValues', 'relatedLinksData', 'nextMatch', 'dataProvider'])

In [ ]:
name = data['name']
birth_date = data['birthDate']['utcTime'][:10]
team = data['primaryTeam']['teamName']

rows = pd.DataFrame({'title': ['Name', 'Birth Date', 'Team'], 'value.fallback': [name, birth_date, team]})

details_data = data['playerInformation']

details_norm_df = pd.json_normalize(details_data)
details_df = details_norm_df[['title', 'value.fallback']]

details_df = pd.concat([rows, details_df])

details_df

            title value.fallback
0            Name     Dylan Tait
1      Birth Date     2001-12-01
2            Team  Dundee United
0          Height         176 cm
1             Age             24
2  Preferred foot          Right
3         Country       Scotland
4    Market value        €644.7k

In [ ]:
# details_df.to_excel('dt_details_df.xlsx', index=False)

In [ ]:
pos_data = data['positionDescription']['positions']

pos_norm_df = pd.json_normalize(pos_data)

pos_df = pos_norm_df.iloc[:,:4]

pos_df

   occurences position  isMainPosition          strPos.label
0          30       64            True  Defensive Midfielder
1           1       77           False    Central Midfielder
2           5       85           False  Attacking Midfielder
3           1       87           False           Left Winger

In [ ]:
# pos_df.to_excel('dt_pos_df.xlsx', index=False)

In [ ]:
heatmap_data = data['firstSeasonStats']['heatmap']['coordinates']

heatmap_df = pd.DataFrame(heatmap_data)

In [ ]:
# heatmap_df.to_excel('df_heatmap.xlsx', index=False)

In [ ]:
shotmap_data = data['firstSeasonStats']['shotmap']

shotmap_df = pd.DataFrame(shotmap_data)

shotmap_df.loc[(shotmap_df['eventType'] == 'AttemptSaved') & (shotmap_df['isBlocked'] == True), 'eventType'] = 'Blocked'

shotmap_df

,id,playerName,eventType,shotType,situation,teamId,playerId,x,y,min,...,awayTeamName,homeScore,awayScore,matchId,matchDate,teamColor,teamColorDark,blockedX,blockedY,minAdded
0,2831679311,Dylan Tait,Goal,LeftFoot,RegularPlay,8596,1037128,93.900000,35.753750,50,...,Dundee United,2,2,4818758,2025-08-03T13:00:00Z,#00366e,#005992,NaN,NaN,NaN
1,2832955209,Dylan Tait,Miss,Header,SetPiece,8596,1037128,96.798246,36.592500,5,...,Falkirk,3,1,4818764,2025-08-09T14:00:00Z,#00366e,#005992,NaN,NaN,NaN
2,2832965121,Dylan Tait,Blocked,Header,FromCorner,8596,1037128,100.543103,28.455000,11,...,Falkirk,3,1,4818764,2025-08-09T14:00:00Z,#00366e,#005992,104.431034,31.407500,NaN
3,2841964241,Dylan Tait,AttemptSaved,RightFoot,RegularPlay,8596,1037128,97.377193,45.612229,50,...,Falkirk,0,1,4818774,2025-08-31T14:00:00Z,#00366e,#005992,103.198276,35.677500,NaN
4,2841982513,Dylan Tait,Blocked,LeftFoot,FromCorner,8596,1037128,91.300000,31.407500,62,...,Falkirk,0,1,4818774,2025-08-31T14:00:00Z,#00366e,#005992,93.500000,31.788750,NaN
5,2841999535,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,94.385965,44.000764,75,...,Falkirk,0,1,4818774,2025-08-31T14:00:00Z,#00366e,#005992,95.640351,43.044375,NaN
6,2852158051,Dylan Tait,AttemptSaved,RightFoot,RegularPlay,8596,1037128,81.471359,37.202500,80,...,Falkirk,3,0,4818788,2025-09-27T14:00:00Z,#00366e,#005992,103.482759,33.695000,NaN
7,2852190439,Dylan Tait,Blocked,LeftFoot,ThrowInSetPiece,8596,1037128,93.000000,27.950714,90,...,Falkirk,3,0,4818788,2025-09-27T14:00:00Z,#00366e,#005992,95.350877,29.295476,5.0
8,2856512461,Dylan Tait,Blocked,RightFoot,FromCorner,8596,1037128,97.280702,42.755313,26,...,Rangers,1,1,4818795,2025-10-05T14:00:00Z,#00366e,#005992,100.637931,39.881190,NaN
9,2860372091,Dylan Tait,AttemptSaved,Header,SetPiece,8596,1037128,91.700000,33.161250,20,...,Falkirk,1,2,4818801,2025-10-18T14:00:00Z,#00366e,#005992,104.146552,34.152500,NaN
10,2863717377,Dylan Tait,Blocked,Header,FromCorner,8596,1037128,99.114035,23.508790,8,...,Dundee FC,2,1,4818806,2025-10-25T14:00:00Z,#00366e,#005992,104.336207,32.246250,NaN
11,2863887657,Dylan Tait,AttemptSaved,RightFoot,RegularPlay,8596,1037128,79.556796,37.050000,64,...,Dundee FC,2,1,4818806,2025-10-25T14:00:00Z,#00366e,#005992,102.913793,33.618750,NaN
12,2866267315,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,78.205340,47.994395,73,...,Falkirk,4,0,4818810,2025-10-29T19:45:00Z,#00366e,#005992,86.030882,43.790573,NaN
13,2870658557,Dylan Tait,Blocked,LeftFoot,FromCorner,8596,1037128,92.200000,30.280000,28,...,Livingston,1,1,4818825,2025-11-08T15:00:00Z,#00366e,#005992,97.859649,31.255000,NaN
14,2874994723,Dylan Tait,Miss,RightFoot,RegularPlay,8596,1037128,82.822816,24.559745,8,...,Falkirk,0,3,4818829,2025-11-22T15:00:00Z,#00366e,#005992,95.254386,34.533750,NaN
15,2875143797,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,82.822816,42.697500,62,...,Falkirk,0,3,4818829,2025-11-22T15:00:00Z,#00366e,#005992,94.385965,37.672000,NaN
16,2879616631,Dylan Tait,Miss,Header,FromCorner,8596,1037128,100.922414,26.400938,11,...,Motherwell,0,0,4818843,2025-12-03T19:45:00Z,#00366e,#005992,NaN,NaN,NaN
17,2879619883,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,72.123786,54.291185,16,...,Motherwell,0,0,4818843,2025-12-03T19:45:00Z,#00366e,#005992,94.482456,39.713095,NaN
18,2884833057,Dylan Tait,Miss,Header,SetPiece,8596,1037128,96.219298,33.313750,24,...,Falkirk,0,1,4818861,2025-12-20T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
19,2886432783,Dylan Tait,Blocked,RightFoot,FromCorner,8596,1037128,82.710194,22.668025,77,...,Falkirk,1,0,4818866,2025-12-27T15:00:00Z,#00366e,#005992,94.964912,29.043333,NaN
20,2887388629,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,90.000000,30.244000,5,...,Aberdeen,1,0,4818878,2026-01-03T15:00:00Z,#00366e,#005992,94.289474,31.102500,NaN
21,2887389581,Dylan Tait,Miss,Header,FromCorner,8596,1037128,101.206897,33.161250,10,...,Aberdeen,1,0,4818878,2026-01-03T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
22,2887391973,Dylan Tait,Miss,RightFoot,RegularPlay,8596,1037128,87.211765,44.981656,15,...,Aberdeen,1,0,4818878,2026-01-03T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
23,2887424465,Dylan Tait,Miss,LeftFoot,RegularPlay,8596,1037128,83.160680,28.791190,61,...,Aberdeen,1,0,4818878,2026-01-03T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
24,2887430901,Dylan Tait,Blocked,RightFoot,SetPiece,8596,1037128,84.512136,21.967389,71,...,Aberdeen,1,0,4818878,2026-01-03T15:00:00Z,#00366e,#005992,95.350877,29.295476,NaN
25,2888474723,Dylan Tait,Blocked,RightFoot,FastBreak,8596,1037128,86.675000,25.533750,18,...,Falkirk,0,2,4818887,2026-01-10T15:00:00Z,#00366e,#005992,88.285294,26.400938,NaN
26,2892223877,Dylan Tait,Miss,RightFoot,RegularPlay,8596,1037128,81.133495,41.225952,12,...,Hibernian,4,1,4818890,2026-01-24T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
27,2899207661,Dylan Tait,Miss,RightFoot,RegularPlay,8596,1037128,74.939320,51.427516,18,...,Dundee FC,1,0,4818908,2026-02-11T19:45:00Z,#00366e,#005992,NaN,NaN,NaN
28,2899223273,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,101.396552,28.370952,35,...,Dundee FC,1,0,4818908,2026-02-11T19:45:00Z,#00366e,#005992,102.818966,30.244000,NaN
29,2899243713,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,91.200000,20.776306,51,...,Dundee FC,1,0,4818908,2026-02-11T19:45:00Z,#00366e,#005992,97.377193,27.026190,NaN
30,2899267623,Dylan Tait,AttemptSaved,RightFoot,RegularPlay,8596,1037128,78.317961,26.400938,84,...,Dundee FC,1,0,4818908,2026-02-11T19:45:00Z,#00366e,#005992,102.913793,32.322500,NaN
31,2905364813,Dylan Tait,Miss,RightFoot,FromCorner,8596,1037128,95.929825,34.000000,17,...,Kilmarnock,5,1,4818925,2026-02-28T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
32,2905385261,Dylan Tait,Blocked,RightFoot,RegularPlay,8596,1037128,88.177941,43.300127,27,...,Kilmarnock,5,1,4818925,2026-02-28T15:00:00Z,#00366e,#005992,92.300000,39.545000,NaN
33,2905386507,Dylan Tait,Goal,LeftFoot,FromCorner,8596,1037128,103.387931,32.703750,28,...,Kilmarnock,5,1,4818925,2026-02-28T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
34,2905469927,Dylan Tait,Goal,RightFoot,FastBreak,8596,1037128,82.935437,25.707187,56,...,Kilmarnock,5,1,4818925,2026-02-28T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
35,2911232017,Dylan Tait,AttemptSaved,RightFoot,RegularPlay,8596,1037128,77.867476,34.991250,53,...,Falkirk,1,1,4818930,2026-03-14T15:00:00Z,#00366e,#005992,103.482759,34.381250,NaN
36,2914584723,Dylan Tait,Miss,LeftFoot,IndividualPlay,8596,1037128,87.641176,34.000000,49,...,St. Mirren,1,2,4818937,2026-03-21T15:00:00Z,#00366e,#005992,NaN,NaN,NaN
37,2919187073,Dylan Tait,Miss,RightFoot,RegularPlay,8596,1037128,82.034466,28.286905,70,...,Falkirk,2,3,4818945,2026-04-04T14:00:00Z,#00366e,#005992,NaN,NaN,NaN
38,2928988823,Dylan Tait,Miss,RightFoot,FromCorner,8596,1037128,81.471359,48.695032,23,...,Falkirk,3,1,5309617,2026-04-25T16:30:00Z,#00366e,#005992,94.096491,41.483438,NaN
39,2928991029,Dylan Tait,Miss,RightFoot,FromCorner,8596,1037128,84.061650,20.285860,26,...,Falkirk,3,1,5309617,2026-04-25T16:30:00Z,#00366e,#005992,NaN,NaN,NaN
40,2929004453,Dylan Tait,Miss,Header,FromCorner,8596,1037128,96.508772,37.583750,43,...,Falkirk,3,1,5309617,2026-04-25T16:30:00Z,#00366e,#005992,NaN,NaN,NaN
41,2932022165,Dylan Tait,Miss,LeftFoot,RegularPlay,8596,1037128,85.816176,26.574375,25,...,Motherwell,1,0,5309621,2026-05-02T14:00:00Z,#00366e,#005992,NaN,NaN,NaN
42,2938146069,Dylan Tait,Miss,RightFoot,FromCorner,8596,1037128,75.277184,41.656875,67,...,Rangers,2,5,5309631,2026-05-16T11:30:00Z,#00366e,#005992,NaN,NaN,NaN

In [ ]:
# shotmap_df.to_excel('dt_shotmap.xlsx', index=False)

In [ ]:
stats_data = data['firstSeasonStats']['statsSection']['items']

stats_df = pd.DataFrame()

for i in range(len(stats_data)):
  stats_df = pd.concat([stats_df, pd.DataFrame(stats_data[i]['items'])], ignore_index=True)

stats_df = stats_df.sort_values(['percentileRankPer90', 'percentileRank'], ascending=False)

stats_df = stats_df.loc[stats_df['percentileRankPer90'] > 65]

stats_df

,localizedTitleId,per90,percentileRank,percentileRankPer90,statFormat,statValue,title
40,red_cards,0.000000,100.000000,100.000000,number,0,Red cards
26,fouls_won,2.668643,100.000000,94.805195,number,80,Fouls won
6,headed_shots,0.266864,94.805195,89.610390,number,8,Headed shots
11,long_balls_accurate,3.936249,96.103896,87.012987,number,118,Accurate long balls
32,recoveries,6.471460,96.103896,87.012987,number,194,Recoveries
33,poss_won_att_3rd_team_title,0.600445,96.103896,77.922078,number,18,Possession won final 3rd
4,shots,1.434396,90.909091,77.922078,number,43,Shots
3,non_penalty_xg,0.119822,89.610390,75.324675,fraction,3.59,xG excl. penalty
23,touches,68.350630,90.909091,74.025974,number,2049,Touches
1,expected_goals,0.119822,88.311688,74.025974,fraction,3.59,xG
29,interceptions,1.100815,89.610390,68.831169,number,33,Interceptions
36,clean_sheet_team_title,0.166790,80.519481,68.831169,number,5,Clean sheets
0,goals,0.100074,81.818182,67.532468,number,3,Goals
19,duel_won,5.604151,90.909091,66.233766,number,168,Duels won

In [ ]:
# stats_df.to_excel('dt_stats_df.xlsx', index=False)