In [1]:
import requests

headers = {
    'sec-ch-ua-platform': '"Windows"',
    'Referer': 'https://www.fotmob.com/en-GB/players/1225025/jonny-yull',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
    'x-mas': 'eyJib2R5Ijp7InVybCI6Ii9hcGkvZGF0YS9wbGF5ZXJEYXRhP2lkPTEyMjUwMjUiLCJjb2RlIjoxNzg0NjI3MTUzNDUxLCJmb28iOiJwcm9kdWN0aW9uOmM5NDE1YjM0NzI4NmI4N2ZmMzYzYWRkNTJiYjNlNDA3NzFmMDU0MmYifSwic2lnbmF0dXJlIjoiQzE5NkI5MjQ3Q0JDNzNGOUMxRUM3NTIxRjgyOEIwRTUifQ==',
    'sec-ch-ua': '"Not;A=Brand";v="8", "Chromium";v="150", "Google Chrome";v="150"',
    'sec-ch-ua-mobile': '?0',
}

params = {
    'id': '1225025',
}

response = requests.get('https://www.fotmob.com/api/data/playerData', params=params, headers=headers)

In [3]:
import os

os.chdir('/content/drive/MyDrive/Football Data Analysis/Jonny Yull')

In [2]:
import pandas as pd

data = response.json()

In [18]:
name = data['name']

birth_date = data['birthDate']['utcTime'][:10]

team = data['primaryTeam']['teamName']

detail_rows = pd.DataFrame({'title': ['Name', 'Birth Date', 'Team'],
               'value.fallback': [name, birth_date, team]})

details_data = data['playerInformation']
details_norm_df = pd.json_normalize(details_data)
details_df = pd.DataFrame(details_norm_df)
details_df = details_df.loc[:, ['title', 'value.fallback']]
details_df = pd.concat([detail_rows, details_df])
details_df

            title   value.fallback
0            Name       Jonny Yull
1      Birth Date       2005-03-05
2            Team  Adelaide United
0          Height           174 cm
1           Shirt               12
2             Age               21
3  Preferred foot            Right
4         Country        Australia
5    Market value          €530.8k

In [19]:
# details_df.to_excel('jy_details_df.xlsx', index=False)

In [27]:
pos_data = data['positionDescription']['positions']

pos_norm_df = pd.json_normalize(pos_data)

pos_df = pd.DataFrame(pos_norm_df)

pos_df = pos_df.iloc[:, :4]

pos_df

   occurences position  isMainPosition        strPos.label
0           5       72           False    Right Midfielder
1           2       74           False  Central Midfielder
2           2       78           False     Left Midfielder
3           4       82           False        Right Winger
4          10       88            True         Left Winger
5           1      106           False             Striker

In [28]:
# pos_df.to_excel('jy_pos_df.xlsx', index=False)

In [34]:
heatmap_data = data['firstSeasonStats']['heatmap']['coordinates']

heatmap_df = pd.DataFrame(heatmap_data)

heatmap_df

          x      y
0     43.55  47.64
1     28.48  65.18
2     48.33  33.47
3     35.92  68.00
4     94.68  60.33
...     ...    ...
1167  72.57  51.85
1168  44.47  64.52
1169  92.20  68.00
1170  71.11  60.26
1171   6.85  30.34

[1172 rows x 2 columns]

In [35]:
# heatmap_df.to_excel('jy_heatmap.xlsx', index=False)